server:
  port: 8080
anaconda:
  address: /home/lmc/anaconda2/bin/python2.7
spring:
  application:
    name: alg
  datasource:
    name: test
    #url: jdbc:mysql://localhost:3306/algorithm-alg?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zsy.alg.entity
logging:
  level:
    tk.mybatis: DEBUG
    com.cnpc.admin: DEBUG
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    # docker 部署开启
    prefer-ip-address: false
    ip-address: localhost
    instance-id: ${spring.application.name}:${CFG_ADMIN_HOST:localhost}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${CFG_EUREKA_HOST:localhost}:${CFG_EUREKA_PORT:8761}/eureka/