spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: http://localhost/limeichao/spring-cloud-config.git
          search-paths: ${CFG_CONFIG_SEARCH_PATH:config}
          username: limeichao
          password: limeichao
server:
  port: 8750
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    # docker 部署开启
    prefer-ip-address: false
    ip-address: localhost
    instance-id: ${spring.application.name}:${CFG_ADMIN_HOST:localhost}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${CFG_EUREKA_HOST:localhost}:${CFG_EUREKA_PORT:8761}/eureka/